/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CRYPTO_H_RPCGEN
#define _CRYPTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct submit {
	int transactionID;
	int ClientID;
	int seed;
};
typedef struct submit submit;

struct transaction {
	int id;
	int challenge;
	int seed;
	int winner;
};
typedef struct transaction transaction;

struct database {
	transaction* table[1000];
	transaction* currentTransaction;	
	int tam;
};
typedef struct database database;

#define PROG 11111111
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define getTransactionID 1
extern  int * gettransactionid_100(void *, CLIENT *);
extern  int * gettransactionid_100_svc(void *, struct svc_req *);
#define getChallenge 2
extern  int * getchallenge_100(int *, CLIENT *);
extern  int * getchallenge_100_svc(int *, struct svc_req *);
#define getTransactionStatus 3
extern  int * gettransactionstatus_100(int *, CLIENT *);
extern  int * gettransactionstatus_100_svc(int *, struct svc_req *);
#define submitChallenge 4
extern  int * submitchallenge_100(submit *, CLIENT *);
extern  int * submitchallenge_100_svc(submit *, struct svc_req *);
#define getWinner 5
extern  int * getwinner_100(int *, CLIENT *);
extern  int * getwinner_100_svc(int *, struct svc_req *);
#define getSeed 6
extern  int * getseed_100(int *, CLIENT *);
extern  int * getseed_100_svc(int *, struct svc_req *);
#define Minerar 7
extern  void * minerar_100(void *, CLIENT *);
extern  void * minerar_100_svc(void *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getTransactionID 1
extern  int * gettransactionid_100();
extern  int * gettransactionid_100_svc();
#define getChallenge 2
extern  int * getchallenge_100();
extern  int * getchallenge_100_svc();
#define getTransactionStatus 3
extern  int * gettransactionstatus_100();
extern  int * gettransactionstatus_100_svc();
#define submitChallenge 4
extern  int * submitchallenge_100();
extern  int * submitchallenge_100_svc();
#define getWinner 5
extern  int * getwinner_100();
extern  int * getwinner_100_svc();
#define getSeed 6
extern  int * getseed_100();
extern  int * getseed_100_svc();
#define Minerar 7
extern  void * minerar_100();
extern  void * minerar_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_submit (XDR *, submit*);

#else /* K&R C */
extern bool_t xdr_submit ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CRYPTO_H_RPCGEN */
