/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "crypto.h"

bool_t
xdr_submit (XDR *xdrs, submit *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->transactionID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ClientID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seed))
		 return FALSE;
	return TRUE;
}
